version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres_fastapi
    volumes:
      - ./db:/var/postgresql/data/
    env_file:
      - ./src/.env

  app:
    build:
      context: .
    image: fastapi
    container_name: fastapi_backend
    command: ["/notes/scripts/app.sh"]
    ports:
      - "2000:8000"
    env_file:
      - ./src/.env
    volumes:
      - .:/notes
    
    depends_on:
      - db
      - redis

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db

  redis:
    image: redis:latest
    container_name: redis_app
    ports:
      - "6378:6379"

  celery:
    build:
        context: .
    command: ["/notes/scripts/celery.sh", "celery"]
    env_file:
      - ./src/.env
    volumes:
      - .:/notes
    container_name: celery_app

    depends_on:
      - redis

  flower:
    build:
        context: .
    command: ["/notes/scripts/celery.sh", "flower"]
    env_file:
      - ./src/.env
    volumes:
      - .:/notes
    container_name: flower_app
    ports:
      - "8888:5555"
    
    depends_on:
      - redis
      - celery
