"""Added rel to user

Revision ID: 665be7f7daf2
Revises: 562987f659a9
Create Date: 2023-07-20 16:19:28.417661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '665be7f7daf2'
down_revision = '562987f659a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('author', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'notes', 'users', ['author'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_column('notes', 'author')
    # ### end Alembic commands ###
