"""init

Revision ID: 693c0403cd7b
Revises: feddd2d7db29
Create Date: 2023-07-24 16:41:22.115060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '693c0403cd7b'
down_revision = 'feddd2d7db29'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
