"""declarative form

Revision ID: d07ac224cc99
Revises: e63632cc4f8f
Create Date: 2023-07-20 18:41:36.537567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd07ac224cc99'
down_revision = 'e63632cc4f8f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
