"""init

Revision ID: feddd2d7db29
Revises:
Create Date: 2023-07-24 15:52:28.522387

"""
from alembic import op
import fastapi_users_db_sqlalchemy
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feddd2d7db29'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('username', sa.String(), nullable=False),
                    sa.Column('first_name', sa.String(), nullable=False),
                    sa.Column('second_name', sa.String(), nullable=True),
                    sa.Column('registered_at', sa.TIMESTAMP(), nullable=True),
                    sa.Column('roles_id', sa.Enum('admin', 'staff', 'user', name='role'), nullable=True),
                    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
                    sa.Column('email', sa.String(length=320), nullable=False),
                    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('is_superuser', sa.Boolean(), nullable=False),
                    sa.Column('is_verified', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('username')
                    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)

    op.create_table('notes',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('priority', sa.Enum('nothing', 'low', 'medium', 'urgent', name='priority'), nullable=True),
                    sa.Column('status', sa.Enum('nothing', 'started', 'in_progress', 'in_review', 'done', name='status'), nullable=True),
                    sa.Column('complexity', sa.Enum('nothing', 'low', 'medium', 'hard', 'extreme', name='complexity'), nullable=True),
                    sa.Column('author', sa.String(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
                    sa.ForeignKeyConstraint(['author'], ['user.username'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('notes')
    # ### end Alembic commands ###
