name: CI

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version-file: '.python-version'
          
      - name: Print name
        run: echo "ENV $TEST_DB_URL"
        env:
          TEST_DB_URL: 'postgresql+asyncpg://postgres:secret@localhost:5432/pytest_fastapi'

      - name: Install flake
        run: pip install flake8

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install --upgrade pip pip-tools
          pip-sync requirements.txt

      - name: Run the linter
        run: |
          . venv/bin/activate
          flake8 ./
    
  test:
    needs: lint
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13.9-alpine
        env:
          POSTGRES_PASSWORD: secret
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version-file: '.python-version'
          
      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install --upgrade pip pip-tools
          pip-sync requirements.txt

      - name: Run the tests
        env:
          TEST_DB_URL: ${{ secrets.DB_URL }}
        run: |
          . venv/bin/activate
          pytest -v ./
